definitions:
  account.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  account.LoginResponse:
    properties:
      accessToken:
        type: string
      accountId:
        type: string
      refreshToken:
        type: string
      userId:
        type: string
    type: object
  account.SignUp:
    properties:
      accountId:
        type: string
      email:
        type: string
      password:
        type: string
      userId:
        type: string
    type: object
  account.SignUpRes:
    properties:
      accessToken:
        type: string
      accountId:
        type: string
      refreshToken:
        type: string
      userId:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/account/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: SignUp Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/account.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.LoginResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Login
      tags:
      - Account
  /api/v1/account/signup:
    post:
      consumes:
      - application/json
      description: SignUp
      parameters:
      - description: SignUp Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/account.SignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.SignUpRes'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: SignUp
      tags:
      - Account
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
